# Generated by Django 3.2.9 on 2021-11-19 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportClubApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctracthor',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='ctracthor',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='ctracthor',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='clase',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuario',
            new_name='id',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='CtrActHor',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
