from .usuarioCreateView import UsuarioCreateView
from .usuarioDetailView import UsuarioDetailView
from .actividadCreateView import ActividadCreateView
from .horarioCreateView import HorarioCreateView
from .ctr_act_horCreateView import CtrActHorCreateView
from .reservaCreateView import ReservaCreateView
from .ctr_act_horDetailView import CtrActHorDetailView
from .ctr_act_horUpdate import CtrActHorUpdateView
from .ctr_act_horDeleteView import CtrActHorDeleteView
from .horarioDeleteView import HorarioDeleteView
from .horarioDetailView import HorarioDetailView
from .horarioUpdateView import HorarioUpdateView
from .ctr_act_horReadAllView import ListaCtrActHorView
from .actividadDetailView import ActividadDetailView
from .horarioReadAllView import ListaHorarioView

